Repository rustyrussell/lnprototest, pull requests merged in 2022-03, with the labels that each got.

#39 Poetry
  .github/workflows/build.yml
  README.md
  docker/Dockerfile.clightning
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
Labels: enhancement, :skull_and_crossbones: Code Cleup :mechanic:

#41 lnprototest: improve the code is the bitcoin core is running
  lnprototest/backend/bitcoind.py
Labels: enhancement

#42 tests: slow down the fixtures scope from session to scope
  tests/conftest.py
Labels: enhancement

#45 clightning Runner: start bitcoind before clightning
  lnprototest/clightning/clightning.py
Labels: :zap: c-lightning :zap:

#46 ci: run the c-lightning integration testing on the latest master
  docker/Dockerfile.clightning
Labels: :hammer: CI/CD :hammer:, :zap: c-lightning :zap:

#47 lnprototest: API improvement and introduction of test utils function
  lnprototest/__init__.py
  lnprototest/clightning/clightning.py
  lnprototest/event.py
  lnprototest/runner.py
  lnprototest/structure.py
  poetry.lock
  pyproject.toml
  tests/helpers.py
  tests/spec_helper.py
  tests/test_bolt7-01-channel_announcement-success.py
  tests/test_bolt7-10-gossip-filter.py
Labels: enhancement, :skull_and_crossbones: Code Cleup :mechanic:, :mechanic: code style :mechanic:
